apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-pvc
  namespace: nginx
  labels:
    app: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
