kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-role
  namespace: apache
rules:
  - apiGroups: ["", "apps", "rbac.authorization.k8s.io", "batch"]
    resources: ["deployments", "pods"]
    verbs: ["get", "watch", "create", "patch"]
