kind: Pod
apiVersion: v1
metadata: 
  name: init-test
spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ["sh", "-c", "echo 'init-container'; sleep 10; echo 'InitContainer Initialized'"]
  containers:
  - name: main-containers
    image: busybox:latest
    command: ["sh", "-c", "echo 'Main containers'"]
