# Use a dedicated namespace and enforce Pod Security.
---
apiVersion: v1
kind: Namespace
metadata:
  name: payments
  labels:
    pod-security.kubernetes.io/enforce: restricted

# Default deny all network traffic (core Zero Trust control)
# Nothing talks to anything unless explicitly allowed.
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: payments
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress


# Explicit allow: frontend → backend only
# Trust is explicit, not implicit.
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-backend
  namespace: payments
spec:
  podSelector:
    matchLabels:
      app: backend
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    ports:
    - protocol: TCP
      port: 8080

# Least-privilege ServiceAccount
# No default service account.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: payments
automountServiceAccountToken: false

# Minimal RBAC (no wildcard permissions)
# Only what the app truly needs.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-reader
  namespace: payments
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-binding
  namespace: payments
subjects:
- kind: ServiceAccount
  name: backend-sa
roleRef:
  kind: Role
  name: backend-reader
  apiGroup: rbac.authorization.k8s.io

# Kubernetes LimitRange (simple & effective)
# Applies defaults if developers forget.
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-resources
  namespace: payments
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"

# Secure Pod spec
# No privilege escalation, no root.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: payments
spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
