kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  labels:
    app: mysql
  namespace: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
